---
version: "3"

services:
    iss-tracker:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: hsosbee/iss-tracker:1.0
        container_name: iss-tracker-app
        ports:
            - "5000:5000"
...
